project:
  type: website

website:
  title: "FPE Analysis"
  navbar:
    left:
      - href: index.qmd
        text: First Pitch Effect

      - href: about.qmd


      - text: FPE Outcomes
        menu:
        - href: hits.qmd
          text: FPE vs Hits
        - href: walks.qmd
          text: FPE vs Walks
        - href: homeruns.qmd
          text: FPE vs Homeruns
        - href: strikeouts.qmd
          text: FPE vs Strikeouts


      - href: videos.qmd
        text: Game Footage

      - href: why_this.qmd
        text: Why This?
      # --- PASTE THE FOOTER HERE (Inside "website") ---
  page-footer:
    background: "black"
    center: "Joshua Hicks, New College of Florida, 2026  | [â˜• Buy me a Coffee](https://venmo.com/u/Joshua-Hicks-243)"
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true


